version: '3'
services:
  web:
    build: 
      context: .
    image: ideacrew/crm:dev-0.0.1    
    links:
      - db
    ports:
      - "3000:3000"
    volumes:
      - gems:/usr/local/rvm/gems
    environment:
      RAILS_ENV: 'development'
      PASSENGER_APP_ENV: 'development'
      DB_DATABASE: 'crm_development'
      DB_USERNAME: 'postgres'
      DB_PASSWORD: 'postgres_local'
      DB_HOST: 'db'
      DB_PORT: 5432
  db:
    image: postgres:12
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=crm_development
      - POSTGRES_PASSWORD=postgres_local
volumes:
  pgdata: {}
  gems: {}
